### PR TITLE
 changed the h5 color to red

### PR DESCRIPTION
**Pull request by mansurissa**

### CODE REVIEW

**Review by 41hulk — APPROVED** [review]
__Great__

**Review by ceelogre — CHANGES_REQUESTED** [review]
'an other' should be one word.

**Review by GuevaraMarius — COMMENTED** [review]
Good

**Comment by mansurissa** [comment]
> 'an other' should be one word.

I'm sorry but I don't know where  i used that (another)?

**Review by ceelogre — APPROVED** [review]

**Comment by ceelogre** [comment]
I've realized it wasn't you who changed it.

**Pull request merged**
